-- CreateEnum
CREATE TYPE "TripItemType" AS ENUM ('FLIGHT', 'HOTEL', 'ACTIVITY', 'RESTAURANT', 'TRANSPORT', 'NOTE', 'OTHER');

-- AlterTable Trip
ALTER TABLE "Trip" ADD COLUMN "name" TEXT NOT NULL DEFAULT 'New Trip';
ALTER TABLE "Trip" ADD COLUMN "notes" TEXT;
ALTER TABLE "Trip" ALTER COLUMN "startDate" DROP NOT NULL;

-- AlterTable TripItem
ALTER TABLE "TripItem" DROP COLUMN "itemType";
ALTER TABLE "TripItem" ADD COLUMN "itemType" "TripItemType" NOT NULL DEFAULT 'OTHER';
ALTER TABLE "TripItem" ALTER COLUMN "dayNumber" SET DEFAULT 1;
ALTER TABLE "TripItem" ADD COLUMN "location" TEXT;
ALTER TABLE "TripItem" ADD COLUMN "cost" DOUBLE PRECISION;
ALTER TABLE "TripItem" ADD COLUMN "currency" TEXT DEFAULT 'USD';
ALTER TABLE "TripItem" ADD COLUMN "notes" TEXT;
ALTER TABLE "TripItem" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "TripItem" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
